version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    # versioning-strategy: lockfile-only
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - ops
