version: "3.2"

volumes:
  bundler:
  pg-data:

networks:
  rails-api:

services:
  api:
    image: "rails-api:dev"
    build:
      context: ../../. # Project root
      dockerfile: .docker/dev/Dockerfile
    volumes:
      - bundler:/rails-api/vendor
      - ../../.:/rails-api
    environment:
      - DATABASE_URL=postgres://rails-api:secret@postgres:5432
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - rails-api

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "rails-api"
      POSTGRES_PASSWORD: "secret"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - rails-api
