version: "3.2"

volumes:
  bundler:
  pg-data:

networks:
  rails-api:

services:
  api:
    image: "rails-api:dev"
    container_name: rails-api
    build:
      context: ../../. # Project root
      dockerfile: .docker/dev/Dockerfile
    volumes:
      - bundler:/rails-api/vendor
      - ../../.:/rails-api
    environment:
      - DATABASE_URL=postgres://postgres:secret@postgres:5432
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/healthz || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - rails-api

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "secret"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rails-api
